Numpy is a Python package useful for numerical analysis. The central object in Numpy is the Numpy array. A Numpy array is like a Python list that can store many data without assigning individual names to the data points, but also more powerful and comes with more convenient functionalities. For example, while adding two Python lists means concatenating them, adding two Numpy arrays, which must be the same length, means adding the elements on the same position:

In [1]:
import numpy as np
import scipy

a = np.array([1,3,3,5,6])
b = np.array([2,8,4,6,9])
a+b

array([ 3, 11,  7, 11, 15])

The random submodule in Numpy also replaces the random package. It can also draw sample random numbers from other types of distribution, such as a normal distribution with any mean and standard deviation:

In [6]:
z = np.random.normal(10,5,100)
z

array([ 6.32661061,  9.22603113, 10.20753968, 15.2987159 , 11.71995738,
       10.08237665,  1.2730159 ,  8.29468201, 11.3348266 , 13.57250763,
       18.12756801,  8.8344966 ,  9.65816501, 11.62704738, 10.7873862 ,
        6.40608349, 12.92403389, 12.8169504 ,  5.73724094, 10.63830116,
       10.06882997,  5.28577132,  8.20066165,  7.30547912,  9.52376403,
        5.25350411, 11.72785505, 11.56155754,  3.71727915,  5.32415184,
        9.58428154, 15.59374174,  7.67125332,  6.77004703, 12.82008549,
       19.20255035, 11.20658359,  4.30911651, 11.59940019,  8.38598113,
       15.62626207, 16.21742913, 14.6361134 ,  3.56297859, 10.30487784,
       10.01509941, 11.32627059,  3.93477757,  5.51552932,  8.54985805,
       14.33844832, -1.3161907 ,  9.42233148,  5.56752074, 15.05572506,
       12.75809277, 12.30482692, 19.49862948,  7.1261972 , 13.46588559,
        7.5569572 , 12.42580985,  4.88674583,  5.51461038, 11.48708075,
        4.75068464,  9.34265276,  7.40918616, 15.29790835, 11.00

Numpy also has a lot of built-in statistical functions widely used in data analysis, such as finding the mean and median:

In [8]:
print(np.mean(z))
print(np.median(z))

10.126156010407772
10.124034592723532


Standard deviation:

In [11]:
np.std(a)

5.280775517006143

Percentile:

In [12]:
np.percentile(a,90)

9.457512704066193

A sister package to Numpy, Scipy, provides more functionalities, notably the Pearson's coefficient of correlation of two Numpy arrays:

In [8]:
a = np.array([1,3,3,5,6])
b = np.array([2,8,4,6,9])

from scipy import stats
stats.pearsonr(a,b)

Numpy regularly uses arrays within arrays, or 2-dimensional arrays. 2-dimensional arrays must be rectangular, and are used to represent matrices in Mathematics. There are two ways of indexing entries in a Numpy array. The first number is the index of row, and the second the index of column:

In [6]:
A = np.array([[1,2],
            [3,4]])
print(A[0,1])
print(A[0][1])

2
2


As matrices are represented by Numpy arrays, there are many Numpy functions that relate to matrices. For example matrix inverse:

In [7]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

And matrix transpose:

In [ ]:
A.T

Read the documentation for more Numpy and Scipy functionalities, especially if you are a math and science enthusiast. Chances are there will be a Numpy or Scipy function already made for your intended use.

Exercise: <br>
Either write a program that counts the number of elements in a Numpy array that are positive, or search for an efficient way to do that in Numpy. <br>
Search the Numpy documentation for the function that computes the eigenvalues of the matrix A above. <br>
Search the Numpy documentation for the function that solves a system of linear equations.