In [2]:
!pip install numpy
!pip install scipy

In [16]:
import numpy as np
import scipy

In [4]:
a = np.array([1,3,3,5,6])
b = np.array([2,8,4,6,9])
a+b

array([ 3, 11,  7, 11, 15])

In [5]:
x = np.arange(0,10,0.1)
y = np.sin(a)
y

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666,
       -0.2794155 , -0.1821625 , -0.0830894 ,  0.0168139 ,  0.1165492 ,
        0.21511999,  0.31154136,  0.40484992,  0.49411335,  0.57

In [9]:
z = np.random.normal(10,5,100)
z

array([18.97630035,  7.17098591,  8.32297533,  5.38153116,  7.52900553,
        0.19953095,  5.08142494, 10.74380111,  3.56823906, 12.51976673,
        9.36261217,  2.15256751, 11.3204758 , 12.80297867, 13.20757297,
       16.59103078,  9.5529102 ,  0.08932325,  6.7734423 , 10.05718219,
        9.84603094, 10.70034853,  7.14595965,  7.39119241,  2.93352918,
       16.96750537,  8.97524215,  2.70085871, -2.33275812, 16.14768901,
        4.52799191, 18.42052139,  7.1422371 ,  4.94416189,  6.04328122,
        2.35109275, 11.27806431,  7.03471829, -1.14175348,  0.11420092,
       12.26586615, 15.13758475, 15.48971848,  6.76153764, 15.71789694,
       11.02493665,  7.57087742, 19.46809648, 11.27981134,  5.98933457,
       10.86971844, 13.10449023,  7.70850572, 15.58585962,  2.82633878,
        3.27530449,  7.44168589,  5.31557465,  4.67794477, -2.08438189,
        6.9969297 , 14.63359871, 16.06848354, 11.82440933, 10.10382604,
        6.94627645, 13.65460422,  7.00392382,  6.05483748,  8.68

In [10]:
np.mean(a)

9.471523527051783

In [11]:
np.std(a)

5.280775517006143

In [12]:
np.percentile(a,90)

9.457512704066193

In [7]:
a = np.array([1,3,3,5,6])
b = np.array([2,8,4,6,9])

In [8]:
from scipy import stats
stats.pearsonr(a,b)

(0.8825200841010356, 0.019891594630031414)